# Generated by Django 5.2.13 on 2026-04-22 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('paystack_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True, default='')),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
