# Generated by Django 5.1.4 on 2026-04-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='hostels/media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hostels/media/thumbs_400/')),
                ('medium', models.ImageField(blank=True, null=True, upload_to='hostels/media/thumbs_1000/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='hostels.hostel')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
