# Generated by Django 5.1.4 on 2026-04-21 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_hostelmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_occupancy', models.PositiveSmallIntegerField(default=1)),
                ('max_occupancy', models.PositiveSmallIntegerField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='hostels.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('locked_k', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_BOOKED', 'Partially Booked'), ('FULL', 'Full'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.roomvariant')),
            ],
            options={
                'unique_together': {('variant', 'label')},
            },
        ),
    ]
