# Generated by Django 5.2.13 on 2026-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expected_check_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
